### ISSUE TITLE
Presentation Review

### ISSUE THREAD

**Issue by jshcrowthe** [jshcrowthe/hacking-http#1]
This is a place for recording comments from content reviewal. 
The actual presentation can be viewed at: http://jshcrowthe.github.io/hacking-http/#1

Feel free to add comments as you see fit!

**Comment by jshcrowthe** [comment]
@lambertsteven: Here is an issue for you to comment on when you get to this!

**Comment by jshcrowthe** [comment]
@redbugz, @spacerockzero: These are my AngularSummit 2015 presentation slides. If you are willing and have a little extra time to go through these and leave me some feedback that'd be great!

**Comment by dncrews** [comment]
Looks good man

**Comment by spacerockzero** [comment]
These slides look awesome! You may be close to the limit of lines of code you should show per slide, as far as text size and legibility from any part of the room, but great deep content presi!

**Comment by redbugz** [comment]
:+1:

**Comment by jshcrowthe** [comment]
Thanks all for your help on this!
